"""
utils/constants.py
Application-wide enum constants and configurations.
"""
ROLES = ("ADMIN", "STUDENT", "LANDLORD")

ACCOUNT_STATUS = ("ACTIVE", "PENDING_VERIFICATION", "SUSPENDED", "DEACTIVATED")

VERIFICATION_STATUS = ("UNSUBMITTED", "PENDING_REVIEW", "APPROVED", "REJECTED", "INFO_REQUIRED")

PROPERTY_TYPES = ("PG", "FLAT", "HOUSE", "HOSTEL", "ROOM")

ROOM_TYPES = ("SINGLE", "DOUBLE_SHARING", "TRIPLE_SHARING", "FOUR_SHARING", "HALL_ROOM")

AVAILABILITY_STATUS = ("AVAILABLE", "OCCUPIED", "INACTIVE")

UTILITY_POLICIES = ("INCLUDED", "FIXED_EXTRA", "METER_SEPARATE", "METER_SHARED")

ALLOWED_RADII_KM = (1.0, 3.0, 5.0, 10.0, 25.0)